-- Migration 050: REVOKE EXECUTE on upsert_user_xp_totals from public roles
--
-- Hotfix for a privilege-escalation bug introduced in migration 046.
-- `upsert_user_xp_totals(UUID, INT, TEXT)` is SECURITY DEFINER and writes
-- user_xp_totals — a table with SELECT-only RLS for users (writes via
-- trigger only, per 042:41-46). PostgREST exposes any non-TRIGGER-returning
-- public-schema function to the authenticated role. Attack path:
--
--     supabase.rpc('upsert_user_xp_totals', {
--       p_user_id: '<any uuid>', p_xp_delta: 999999, p_event_type: 'scan'
--     })
--
-- Any authenticated user can call the helper and inflate their own totals,
-- tamper with other users' totals, or spike scans_count/discoveries_count/
-- contributions_count. This defeats the trigger-only write contract.
--
-- Fix: REVOKE EXECUTE from PUBLIC, anon, authenticated.
--
-- Why all three: Supabase's initial project setup runs
--   GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;
--   ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON ROUTINES TO anon, authenticated, service_role;
-- so any function created in public schema receives an explicit grant to
-- anon + authenticated. Revoking from PUBLIC alone does NOT override the
-- explicit role grants — we must name the roles directly.
--
-- service_role is intentionally left with EXECUTE: it is server-side only
-- (Edge Functions / admin tooling). If we ever need to call the helper
-- outside the trigger chain, service_role is the caller.
--
-- Trigger functions in 046 are SECURITY DEFINER owned by postgres and call
-- this helper via PERFORM, so they run with owner privileges and are
-- unaffected by this revoke. No legitimate direct-caller breakage.
--
-- Cache invalidation not needed: does not affect pet_product_scores inputs.

REVOKE EXECUTE ON FUNCTION upsert_user_xp_totals(UUID, INT, TEXT) FROM PUBLIC, anon, authenticated;
